(defun my-setup-c-mode ()
  ;; (c-set-style "linux")
  (setq whitespace-indent-tabs-mode t)
  (imenu-add-menubar-index)
  (column-marker-1 80)
  (setq comment-style 'extra-line)
  (add-hook 'before-save-hook 'whitespace-cleanup nil t)
  (local-set-key (kbd "RET") 'newline-and-indent)
  (subword-mode)
  (local-set-key (kbd "<backtab>") 'clang-format-region)
  (set-fill-column 78))

(add-hook 'c-mode-common-hook 'my-setup-c-mode)
(add-to-list 'auto-mode-alist '("\\.x$" . c-mode))
